package com.facetec.sdk;

/* renamed from: com.facetec.sdk.de */
enum C2942de {
    YOUR_ZOOM_IMAGE_OVERRIDE,
    CLICKABLE_READY_SCREEN_SUBTEXT,
    DEV_MODE_TAG,
    UNCONSTRAINED_GUIDANCE_STRING_LENGTHS,
    STANDALONE_IDSCAN_WATERMARK_CUSTOMIZATION,
    ENABLE_SCREEN_CAPTURING
}
