package ek0;

/* renamed from: ek0.a */
public enum C20261a {
    NOT_ADDED,
    TOKEN_STATE_ACTIVE,
    TOKEN_STATE_NEEDS_IDENTITY_VERIFICATION,
    TOKEN_STATE_PENDING,
    TOKEN_STATE_SUSPENDED,
    TOKEN_STATE_FELICA_PENDING_PROVISIONING,
    TOKEN_STATE_UNTOKENIZED,
    WALLET_NEEDS_CREATION,
    WALLET_NOT_AVAILABE
}
