package dk0;

/* renamed from: dk0.a */
public enum C20031a {
    CARD_NETWORK_AMEX,
    CARD_NETWORK_DISCOVER,
    CARD_NETWORK_MASTERCARD,
    CARD_NETWORK_QUICPAY,
    CARD_NETWORK_PRIVATE_LABEL,
    CARD_NETWORK_VISA
}
